<div class="_rp_15 ms-font-weight-regular ms-font-color-neutralDark rpHighlightAllClass rpHighlightBodyClass" id="Item.MessageUniqueBody" style="font-family: &quot;wf_segoe-ui_normal&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif, serif, &quot;EmojiFont&quot;;"><div>
<div link="#0563C1" vlink="#954F72" lang="en-US">
<div>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">Good afternoon,</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">&nbsp;</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">We are excited to announce policy changes regarding <b>Sabbaticals &amp; Rewards</b> that will go into effect on Friday, July 12<sup>th</sup>, 2019.</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">&nbsp;</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;"><b>Please make yourself aware of the new policy as you may qualify for new rewards.</b></p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">&nbsp;</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">Learn more here: <a href="{{ url.webserver }}" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable">OneLogin (Portal)</a></p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">&nbsp;</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">Thanks,</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;">&nbsp;</p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;"><b><span style="color: rgb(27, 74, 132); font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;;">{{ sender.friendly_alias }} </span></b><span style="color: rgb(102, 104, 102); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da">Sr.
<span class="highlight" id="0.17160256477735913" name="searchHitInReadingPane">Human</span> <span class="highlight" id="0.47878462797623556" name="searchHitInReadingPane">Resources</span> Generalist &amp; Development Specialist</span><b><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;;"></span></b></p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;"><b><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da">e: </span></b><a href="mailto:{{ sender.friendly_alias }}" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable"><span style="font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">{{ sender.email }}</span></a><span style="color: rgb(15, 183, 198); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">
</span><b><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da">p: </span></b><span style="color: rgb(102, 104, 102); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da">+1.555.555.5555</span><span style="color: rgb(238, 123, 53); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da">
</span><span style="color: rgb(102, 104, 102); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;" lang="da"></span></p>
<p style="font-size: 11pt; font-family: Calibri, sans-serif, serif, &quot;EmojiFont&quot;; margin: 0px;"><b><span style="color: rgb(27, 74, 132); font-size: 6pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;"><br>

</span></b><b><span style="color: rgb(27, 74, 132); font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">Company</span></b><b><span style="color: rgb(238, 123, 53); font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">&amp</span></b><b><span style="color: rgb(27, 74, 132); font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">NAME</span></b><b><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;"> </span></b><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">-</span><b><span style="color: rgb(31, 73, 125); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">
</span></b><a href="http://www.COMPANY.com" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable"><span style="font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">www.COMPANY.com</span></a><span style="color: rgb(15, 183, 198); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">
</span><span style="color: rgb(27, 74, 132); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">-<b> </b></span><a href="https://www.linkedin.com/company/NAMEOFCOMPANY" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable"><span style="color: rgb(15, 183, 198); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;">Follow
us on LinkedIn</span></a><u><span style="color: rgb(15, 183, 198); font-size: 10pt; font-family: Arial, sans-serif, serif, &quot;EmojiFont&quot;; background-color: white;"></span></u></p>
</div>
</div>
</div>
</div>
